version: 2.1
# orbs:
#   docker-buildx: sensu/docker-buildx@1.1.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04

    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      # - docker-buildx/install
      - run:
          name: "Preview"
          command: docker buildx ls
      # - run:
      #     name: "add builder"
      #     command: docker context ls
          # command: docker context create default && docker context use default
      - run:
          name: "add builder"
          command: docker buildx create --use --name builder default
      - run:
          name: "build"
          command: docker buildx build --platform linux/amd64,linux/arm64 -t ci-buildx-checker:latest .

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
