version: 2.1
# orbs:
#   docker-buildx: sensu/docker-buildx@1.1.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04

    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      # - docker-buildx/install
      - run:
          name: "Preview"
          command: docker buildx ls
      - run:
          name: "create context"
          command: |
            docker context create my-context \
              --docker "host=${DOCKER_HOST},ca=${DOCKER_CERT_PATH}/ca.pem,cert=${DOCKER_CERT_PATH}/cert.pem,key=${DOCKER_CERT_PATH}/key.pem"
      - run:
          name: "use my-context"
          command: docker context use my-context
      - run:
          name: "add builder"
          command: docker --context my-context buildx create --use --name builder
      - run:
          name: "build"
          command: docker --context my-context buildx build --platform linux/amd64,linux/arm64 -t ci-buildx-checker:latest --output=type=local,dest=./ .
      - run:
          name: "list"
          command: ls

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
