version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    environment:
      BUILDX_PLATFORMS: "linux/amd64,linux/arm64"

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "add builder"
          command: docker buildx create --use --name builder
      - run:
          name: "build"
          command: docker buildx bake --no-cache --load
      - run:
          name: "list"
          command: docker image ls

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
