version: 2.1
orbs:
  docker-buildx: sensu/docker-buildx@1.1.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04

    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      # - docker-buildx/install
      - run:
          name: "Preview"
          command: docker buildx ls

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
